config/routes.rb
Rails.application.routes.draw do

  get 'homes/about'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  # get 'password_resets/new'

  # get 'password_resets/edit'

  require 'sidekiq/web'
  if Rails.env.production?
    mount Sidekiq::Web => 'sidekiq'
  end
  mount ApiRoot => '/api'
  mount GrapeSwaggerRails::Engine, at: "/doc"
  post '/get_sms_code', to: "users#get_sms_code"
  post '/password_resets_code', to: "password_resets#password_resets_code"
  get '/check_name', to: 'users#check_name'
  get '/check_email', to: 'users#check_email'
  get '/check_phone', to: 'users#check_phone'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end
	
  concern :commentable do
    resources :comments, concerns: [:likeable]
  end

  resources :articles, concerns: [:likeable, :commentable]
  resources :comments, concerns: [:likeable]
  resources :users do
    resources :articles do
    collection do
      get :release
    end
    end
    member do
      get :person
      get :profile
      post :checkin
    end
  end

  resources :sessions
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  resource :password_resets
   
  root "articles#index"
  get "welcome", to: "welcomes#index"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin do
    root "welcomes#index"
    resources :welcomes
    resources :users do
      member do
       get :rencent_new_user
      end
    end
    resources :articles do
      member do
        patch :complete
        post :deny
    end
  end
    resources :comments
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Likeable
  include Redis::Objects
  include SimpleRecommender::Recommendable
  similar_by :users
  set :limit_read
  # extend FriendlyId
  # friendly_id :title
  counter :click_count
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, as: 'likeable', dependent: :destroy
  has_many :users, through: :likes
  validates :title, presence: true, length: { in: 3..11 }
  validates :content, presence: true
  validates :avatar, attachment_presence: true
  has_attached_file :avatar, styles: { :original => '300x300>', :small => "200x200#" }
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/png", "image/jpeg"]
  validates_attachment_size :avatar, less_than: 5.megabytes
  enum status:[:audit, :complete, :deny]

  def is_user_like?(user)
    likes.map(&:user_id).include? user&.id
  end

  def view!
    self.increment!(:views_count)
  end

  def self.random_saying
    %w(知之者不如好之者，好之者不如乐之者。——孔子 一次失败，只是证明我们成功的决心还够坚强。——博维 
        成功的唯一秘诀——坚持最后一分钟。——柏拉图).sample
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController

  def index
    @articles = Article.all.page(params[:page]).per(3)
  end

  def show
    @article = Article.find(params[:id])
  end

  def complete
    @article = Article.find(params[:id])
    if @article.audit? || @article.deny?
      @article.complete! 
      flash[:success] = "审核通过"
      redirect_to admin_articles_path
    end
  end

  def deny
    @article = Article.find(params[:id])
    if @article.audit? || @article.complete?
      @article.deny! 
      flash[:danger] = "已拒绝"
      redirect_to admin_articles_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show, :release]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :destroy]

  def index
    if params[:category].blank?
      @q = Article.ransack(params[:q])
      @articles = @q.result.includes(:user, :comments).order(created_at: :desc).page(params[:page]).per(3)
      @users = User.order_by_ids(User.ranks.members.reverse) #用户积分排序
    else
      @category_name = params[:category]
      @category_id = Category.where(name: params[:category]).first&.id
      @articles = Article.where(category_id: @category_id).order(created_at: :desc).page(params[:page]).per(3)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @article = Article.new
  end

  def show
    unless cookies["view-article-#{@article.id}"]
      cookies["view-article-#{@article.id}"] = "true"
      @article.view!
    end
    if current_user
      unless @article.limit_read.member?("#{current_user.id}")   # 判断当前用户是否在该集合中
        current_user.ranks.incr("#{current_user.id}", 3)     # 当前用户的积分数
        @article.limit_read << current_user.id  # 把当前用户写入集合中
      end
      @article.click_count.incr() # 添加用户的阅读量
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
      flash[:success] = "创建成功"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to root_url
      @article.update(created_at: Time.zone.now)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  def release
    @user = User.friendly.find(params[:user_id])
    @releases = @user.articles
  end


  private

  def article_params
    params.require(:article).permit(:title, :content, :category_id, :avatar)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def current_copyright_year
    Date.today.year
  end
end

app/views/admin/articles/index.html.haml
= render 'shareds/flash'
.container-fluid
  .row
    .col-md-8.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h3.panel-title
          %span 所有文章

        .panel-body
          %table.table.table-hover.table-striped
            .thead
              %tr
                %th ID
                %th 标题
                %th 类型
                %th 点击量
                %th 状态
                %th 
            .tbody
              - @articles.each do |article|
                %tr
                  %td= article.id
                  %td= article.title
                  %td= article.category&.name
                  %td= article.click_count
                  %td= I18n.t("admin.articles.status.#{article.status}")
                  %td= link_to "进入审查", admin_article_path(article), class: "btn btn-primary btn-xs"

          = paginate @articles
        = pie_chart Article.group_by_week(:created_at).count
       

app/views/admin/articles/show.html.haml
- content_for(:title, @article.title)
.container-fluid
  .row
    .col-md-8.col-md-offset-3
      .panel.panel-default
        .panel-heading
          .panel-title
          %span文章
        .panel-body
          %table.table.table-striped
            .thead
              %tr
                %th标题
                %th内容
                %th图片
            .tbody
              %tr
                %td=@article.title
                %td=@article.content
                %td= image_tag @article.avatar.url
              %tr
                %td{:colspan => 6}
                  = link_to "通过", complete_admin_article_path(@article), method: :patch, class: "btn btn-primary"
                  = link_to "拒绝", deny_admin_article_path(@article), method: :post, class: "btn btn-danger"