config/routes.rb
Rails.application.routes.draw do

  get 'homes/about'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  # get 'password_resets/new'

  # get 'password_resets/edit'

  require 'sidekiq/web'
  if Rails.env.production?
    mount Sidekiq::Web => 'sidekiq'
  end
  mount ApiRoot => '/api'
  mount GrapeSwaggerRails::Engine, at: "/doc"
  post '/get_sms_code', to: "users#get_sms_code"
  post '/password_resets_code', to: "password_resets#password_resets_code"
  get '/check_name', to: 'users#check_name'
  get '/check_email', to: 'users#check_email'
  get '/check_phone', to: 'users#check_phone'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end
	
  concern :commentable do
    resources :comments, concerns: [:likeable]
  end

  resources :articles, concerns: [:likeable, :commentable]
  resources :comments, concerns: [:likeable]
  resources :users do
    resources :articles do
    collection do
      get :release
    end
    end
    member do
      get :person
      get :profile
      post :checkin
    end
  end

  resources :sessions
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  resource :password_resets
   
  root "articles#index"
  get "welcome", to: "welcomes#index"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin do
    root "welcomes#index"
    resources :welcomes
    resources :users do
      member do
       get :rencent_new_user
      end
    end
    resources :articles do
      member do
        patch :complete
        post :deny
    end
  end
    resources :comments
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Likeable
  include Redis::Objects
  include SimpleRecommender::Recommendable
  similar_by :users
  set :limit_read
  # extend FriendlyId
  # friendly_id :title
  counter :click_count
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, as: 'likeable', dependent: :destroy
  has_many :users, through: :likes
  validates :title, presence: true, length: { in: 3..11 }
  validates :content, presence: true
  validates :avatar, attachment_presence: true
  has_attached_file :avatar, styles: { :original => '300x300>', :small => "200x200#" }
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/png", "image/jpeg"]
  validates_attachment_size :avatar, less_than: 5.megabytes
  enum status:[:audit, :complete, :deny]

  def is_user_like?(user)
    likes.map(&:user_id).include? user&.id
  end

  def view!
    self.increment!(:views_count)
  end

  def self.random_saying
    %w(知之者不如好之者，好之者不如乐之者。——孔子 一次失败，只是证明我们成功的决心还够坚强。——博维 
        成功的唯一秘诀——坚持最后一分钟。——柏拉图).sample
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController

  def index
    @articles = Article.all.page(params[:page]).per(3)
  end

  def show
    @article = Article.find(params[:id])
  end

  def complete
    @article = Article.find(params[:id])
    if @article.audit? || @article.deny?
      @article.complete! 
      flash[:success] = "审核通过"
      redirect_to admin_articles_path
    end
  end

  def deny
    @article = Article.find(params[:id])
    if @article.audit? || @article.complete?
      @article.deny! 
      flash[:danger] = "已拒绝"
      redirect_to admin_articles_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index, :show, :release]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :destroy]

  def index
    if params[:category].blank?
      @q = Article.ransack(params[:q])
      @articles = @q.result.includes(:user, :comments).order(created_at: :desc).page(params[:page]).per(3)
      @users = User.order_by_ids(User.ranks.members.reverse) #用户积分排序
    else
      @category_name = params[:category]
      @category_id = Category.where(name: params[:category]).first&.id
      @articles = Article.where(category_id: @category_id).order(created_at: :desc).page(params[:page]).per(3)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @article = Article.new
  end

  def show
    unless cookies["view-article-#{@article.id}"]
      cookies["view-article-#{@article.id}"] = "true"
      @article.view!
    end
    if current_user
      unless @article.limit_read.member?("#{current_user.id}")   # 判断当前用户是否在该集合中
        current_user.ranks.incr("#{current_user.id}", 3)     # 当前用户的积分数
        @article.limit_read << current_user.id  # 把当前用户写入集合中
      end
      @article.click_count.incr() # 添加用户的阅读量
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
      flash[:success] = "创建成功"
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to root_url
      @article.update(created_at: Time.zone.now)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to @article
  end

  def release
    @user = User.friendly.find(params[:user_id])
    @releases = @user.articles
  end


  private

  def article_params
    params.require(:article).permit(:title, :content, :category_id, :avatar)
  end

  def find_article
    @article = Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def current_copyright_year
    Date.today.year
  end
end

app/views/articles/_article.html.haml
- cache article, expires_in: 1.minute do
  .panel.body
    %ul.list-group
      .list-group-item
        .media-left
          - if article.user.image.blank?
            = image_tag('avatar.png', class: "img-rounded", width: 64, height: 64)
          - else
            = image_tag(article.user.image, class: "img-rounded", width: 64, height: 64) if article.user
        .media-body
          .media-heading.find-more
            = article.title
            by
            = article.user&.name
            = link_to "查看更多...", article, class: "btn btn-primary btn-xs much-more", id: "score",
            "data-original-title" => "读取文章积分+3"
          .media-heading#item
            最后由
            = article.last_username
            回复于
            = time_ago_in_words(article.created_at)
            前
        #index1
          %span.badge.badge-info= article.category&.name
          //%span.badge.badge-success= I18n.t("articles.status.#{article.status}")
          %span
            = article.comments.count
            = t('.Comments')
          %span= time_ago_in_words(article.created_at) + "之前" 

- if login?
  :javascript
    $(document).ready(function(){
      $("#score").tooltip('toggle')
    });

app/views/articles/_bottom.html.erb
<div class="bottom">
  <h5>需要<%= link_to "登录", login_path, class: "btn btn-danger" %>才能评论</h5>
</div>

app/views/articles/_comment_text.html.haml
- if login?
  = simple_form_for([@article, @article.comments.build], remote: true) do |f|
    .form-group
      = f.hidden_field :comment_id, value: nil
    .form-group
      %i.glyphicon.glyphicon-comment
      = f.label :评论
      %br
        = f.text_area :content, placeholder: "评论内容...", class: "form-control"
        %div.limit
    = f.submit t('.create comment'), class: "btn btn-primary"
    = link_to t('.B'), root_path, class: "btn btn-danger"
- else
  = render "articles/bottom"

#article
  - if correct_user
    = link_to edit_article_path(@article) do
      %i.fa.fa-edit
  
    = link_to article_path(@article), method: :delete, data: { confirm: "确定删除?" } do
      %i.fa.fa-trash

app/views/articles/_form.html.haml
- content_for(:title, "新建文章")
.main
  .container
    .row
      .col-md-6.col-md-offset-3
        .panel.panel-default
          .panel-heading
            %h2= t('.publish')
          .panel-body
            = form_for @article, html: { multipart: true, id: "edit_article" } do |f|
              .form-group
                = f.label :类型, class: "control-label"
                = f.collection_select :category_id, Category.all, :id, :name, 
                class: "form-control", :include_blank => "请选择..."

              .form-group
                = f.label :标题, class: "control-label"
                = f.text_field :title, class: "form-control", title: "标题不能为空", "data-placement" => "bottom"

              .form-group
                = f.label :内容, class: "control-label"
                = f.text_area :content, id: 'editor', class: "form-control", placeholder: "新建内容..."
                &nbsp
                = f.file_field :avatar
              = f.submit t('.publish'), class: "btn btn-primary"

:javascript
  editor = new Simditor({
    textarea: $('#editor')
  });

  $("#edit_article").validate({
    rules: {
      'article[title]': { 
        required: true,
        minlength: 4,
      }
    },
    messages: {
      'article[title]': { 
        required: "标题不能为空",
        minlength: "最短长度为11个字符",
      },
    }
  });

  $('#article_category_id').select2();

app/views/articles/_like.html.haml
- if @article.is_user_like?(current_user)
  .span-count
    = link_to article_like_path(@article), method: :delete, "class" => "like", "id" => "like_article_btn_#{@article.id}", remote: true do
      %i.fa.fa-heart.like_article{ id: "like_article_#{@article.id}", style: "color:red;" }
  .span-count
    %p{id: "like_article_#{@article.id}_count"}= @article.likes.count
    .user-avatar
      - @article.likes.each do |like|
        - if like.user.image.present?
          = image_tag like.user.image.url, width: 20, title: like.user.name, id: "user_#{like.user_id}"
- else
  = link_to article_like_path(@article), method: :post, "class" => "like", "id" => "like_article_btn_#{@article.id}", remote: true do
    %i.fa.fa-heart.like_article{ id: "like_article_#{@article.id}" }
    .span-count
      %p{id: "like_article_#{@article.id}_count"}= @article.likes.count
      .user-avatar
        - @article.likes.each do |like|
          - if like.user.image.present?
            = image_tag like.user.image.url, width: 20, title: like.user.name

app/views/articles/edit.html.haml
.row
  .col-md-15
    .panel.panel-wikis
      .panel-heading
        编辑
      = render 'shareds/article_errors'
      .panel-body
        = simple_form_for(@article) do |f|
          .form-group
            = f.label :标题, class: "control-label"
            = f.text_field :title, class: "form-control"

          .form-group
            = f.label :内容, class: "control-label"
            = f.text_area :content, id: "editor", class: "form-control"

          .form-group
            = f.file_field :avatar

          = f.submit t('.publish'), class: "btn btn-primary btn-sm"
          = link_to "取消", article_path, class: "btn btn-info btn-sm"
:javascript
  editor = new Simditor({
    textarea: $("#editor")
  });

app/views/articles/index.html.haml
.modal.fade.bs-example-modal-sm{ id: "signin", tabindex: "-1", role: "dialog", 'aria-labelledby' => "mySmallModalLabel" }
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button{class: "close", 'data-dismiss' => "modal", 'aria-label' => "Close", 'aria-hidden' => "true"} &times
        %h4.modal-title 用户登录
      .modal-body.modal-login
        = form_tag(sessions_path, method: :post) do
          .form-group
            %div{class: "input-group"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-phone
              = search_field_tag :login, params[:login], class: "form-control", value: cookies.permanent[:phone], placeholder: '手机号码/邮箱...'
          .form-group
            %div{class: "input-group"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-lock
              = password_field_tag :password, nil, class: "form-control", placeholder: '密码'
          = link_to "忘记密码?", new_password_resets_path
          .form-group
            = label_tag :记住我
            = check_box_tag :remember_me, 1, params[:remember_me]
            
          = submit_tag '登录', class: "btn btn-primary", data: {disable_with: "登录中..."}

.main
  .container
    = render 'shareds/flash'
    #bg-img
      .carousel.slide{:id=>"slide-images", :data => {:ride => "carousel"}}
        .carousel-inner
          .item.active
            = image_tag("zjj.jpg", style: "width: 1440px")
          .item
            = image_tag("new2.jpeg", style: "width: 1440px")
          .item
            = image_tag("new.jpg", style: "width: 1440px")
          .item
            = image_tag("new1.jpeg", style: "width: 1440px")

          %a.right.carousel-control{:href => "#slide-images", :data => {:slide => "next"}}
            %span.glyphicon.glyphicon-chevron-right

    .row
      .col-md-9
        .panel.panel-wikis
          .panel-heading
            %h2= t('.All article')
            = search_form_for(@q, remote: true) do |f|
              = f.search_field :title_or_user_name_or_comments_content_cont, placeholder: t('.search_body')
              = f.submit t('.search'), class: "btn btn-primary"
          
          #tbody
            = render @articles
          #paginator
            = paginate @articles, remote: true
      .col-md-3
        - unless login?
          .panel.panel-default
            .panel.body
            #marquee
              #announcement
                众志成城 共克时艰
          .panel.panel-default
            .panel-body
              .JQ
          .panel.panel-default
            .panel-body
              .greetings
              .solar_date
              .lunar_date
        .panel.panel-wikis
        .panel.panel-default
          .panel-body
            = link_to "发布新文章", new_article_path, class: 'btn btn-primary btn-block'

        .panel.panel-wikis
        .panel.panel-default
          .panel-heading.clearfix{style: "height: 35px"}
            %span 一切从这里开始
          .panel-body
            = Article.random_saying
        - unless login?
          .panel.panel-wikis
          .panel.panel-default
            .panel-heading.clearfix
              %span积分排行榜
              .pull-right
                = image_tag "jf.jpg", class: 'img-rounded', width: 60, height: 60, class: "jf"
            .panel-body
              %table.table.table-striped
                %thead
                  %tr
                    %th 排名
                    %th 积分
                    %th 用户
                %tbody
                  - User.all.each do |user|
                    %tr
                      %td= user.rank
                      %td= (user.score)+(user.checkin_score.score(user.id).to_i)
                      %td= link_to user.name, user_path(user)
                
          .panel.panel-wikis
          .panel.panel-default
            .panel-heading.clearfix{style: "height: 35px"}
              %span源码地址
            .panel-body
              %a{:href => "https://www.github.com/qqgwq/wiki"}请点击这里

          .panel.panel-default
            .panel-heading{style: "height: 35px"}
              统计信息
            %ul.list-group
              %li.list-group-item
                论坛人数:
                = User.count
                人
              %li.list-group-item
                帖子数:
                = Article.count
                个
              %li.list-group-item
                回帖数:
                = Comment.count
                条

        - if login?
          %ul.list-group#categories
            %li= link_to "所有文章", root_path, class: "list-group-item"
            - Category.all.each do |category|
              %li= link_to category.name, articles_path(category: category.name), remote: true, class: "list-group-item"

app/views/articles/index.js.erb
$(".list-group-item").css("background", "white");

<% if params[:category] %>
 $("#categories a:contains(<%= params[:category] %>)").css("background", "red");
<% else %>
 $("#categories a").css("background", "white");
<% end %>

$("#tbody").html('<%= escape_javascript render(@articles)%>');
$("#paginator").html('<%= escape_javascript(paginate @articles, remote: true) %>');

app/views/articles/new.html.haml
= render 'form'

app/views/articles/release.html.haml
.row
  .col-md-9
    .panel.panel-wiki
    .panel.panel-default
      .panel-heading.clearfix
        %span
          = @user&.name
        的文章
      - if @releases.present?
        - @releases.each do |release|
          %ul.article_list.list-group
            %li.list-group-item-wiki.media{style: "border-bottom: 1px solid #ddd; padding: 10 15"}
              .media-left
                .media-heading
                  - if release.user.image.present?
                    = image_tag release.user.image.url, class: 'img-rounded', width: 48, height: 48
                  - else
                    = image_tag("avatar.png", class: 'img-rounded', width: 48, height: 48)
              .media-body
                %h4.media-heading
                  = link_to release.title, article_path(release)
                .media-heading.small
                  = release.user.name
                  的文章于
                  = release.created_at.to_date
                  更新
      - else
        该用户很懒, 没有发布任何文章

app/views/articles/show.html.haml
- content_for(:title, @article.title)
.main
  .container
    .row
      .col-md-9
        .panel.panel-wiki2
          = render 'shareds/flash'
          .panel.panel-default
            .panel-heading
              .panel-title
              = @article.title
              = link_to(@article.url, @article.url, target: :_blank)

              #article-img
                - if @article.user.image.present?
                  = link_to(image_tag @article.user.image.url, title: @article.user.name)
                - else
                  = image_tag("avatar.png", class: 'img-rounded', width: 48, height: 48)
            .info
              = @article.user.name
              &nbsp
              发布于
              = @article.created_at.to_date
              &nbsp
              = @article.views_count
              次阅读
              &nbsp
              点击量
              = @article.click_count.value()
              次
            %ul.list-group
              %li.list-group-item-wiki.media{style: "padding: 8"}
                .media-left 
                  = image_tag @article.avatar.url, width: 164, height: 164, class: 'img-rounded'
                .media-body
                  .pull-right
                    = render partial: 'articles/like'
                  .media-heading
                    = raw @article.content
                #comments
                  = render partial: 'comments/comment', collection: @article.comments, :as => :comment
              
              .panel.panel-wiki#comment-text
                .panel.panel-default
                  .panel-heading
                    .panel-title
                    #counts 
                      共
                      = @article.comments.count
                      条评论

        .need-login
          .panel
            .panel-body
              = render "comment_text"
        .card
          .panel
            .panel-heading
              %span 猜你喜欢
            .panel-body
              %ul.list-group.list-group-flush
                - @article.similar_items(n_results: 5).each do |article|
                  %li.list-group-item
                    = link_to article.title, article.url
                 

      .col-md-3
        .panel.panel-wiki2
          .panel.panel-default
            .panel-heading
              %span 分享到
            .panel-body
              = social_share_button_tag(@article.title)