config/routes.rb
Rails.application.routes.draw do

  get 'homes/about'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  # get 'password_resets/new'

  # get 'password_resets/edit'

  require 'sidekiq/web'
  if Rails.env.production?
    mount Sidekiq::Web => 'sidekiq'
  end
  mount ApiRoot => '/api'
  mount GrapeSwaggerRails::Engine, at: "/doc"
  post '/get_sms_code', to: "users#get_sms_code"
  post '/password_resets_code', to: "password_resets#password_resets_code"
  get '/check_name', to: 'users#check_name'
  get '/check_email', to: 'users#check_email'
  get '/check_phone', to: 'users#check_phone'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end
	
  concern :commentable do
    resources :comments, concerns: [:likeable]
  end

  resources :articles, concerns: [:likeable, :commentable]
  resources :comments, concerns: [:likeable]
  resources :users do
    resources :articles do
    collection do
      get :release
    end
    end
    member do
      get :person
      get :profile
      post :checkin
    end
  end

  resources :sessions
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  resource :password_resets
   
  root "articles#index"
  get "welcome", to: "welcomes#index"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin do
    root "welcomes#index"
    resources :welcomes
    resources :users do
      member do
       get :rencent_new_user
      end
    end
    resources :articles do
      member do
        patch :complete
        post :deny
    end
  end
    resources :comments
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
end

app/models/user.rb
class User < ApplicationRecord 
  #before_destroy :no_referenced_comments
  include Redis::Objects
  sorted_set :ranks, :global => true
  sorted_set :checkin_score, :global => true
  attr_accessor :verification_code
  include Concerns::AuthToken
  extend FriendlyId
  friendly_id :name
  has_secure_password
  has_many :articles, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :notifications
  has_many :likes
  has_many :like_articles, through: :likes, source: :likeable, source_type: "Article"
  validates :name, :phone, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 1..11 }, on: :create
  validates :verification_code, presence: true, on: :create
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  #validates :image, attachment_presence: true
  has_attached_file :image, styles: { :original => '250x250>', :small => "200x200#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/png", "image/jpeg"]
  validates_attachment_size :image, less_than: 5.megabytes
  before_create { generate_token(:auth_token) }
  after_create :init_score

  enum gender: ["male", "female"]


  def admin?
    is_admin
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.rencent_user
    User.where("created_at > ?", Time.current.ago(1.day))
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << column_names
    all.each do |user|
      csv << user.attributes.values_at(*column_names)
      end
    end
  end

  def name=(value)
    write_attribute :name, value
    write_attribute :name_lower, value.downcase
  end

  def email=(value)
    write_attribute :email, value
    write_attribute :email_lower, value.downcase
  end

  #postgres 排序
  def self.order_by_ids(ids)
    order_by = ["case"]
    ids.each_with_index.map do |id, index|
      order_by << "WHEN id='#{id}' THEN #{index}"
    end
    order_by << "end"
    order(order_by.join(" "))
  end

  #用户排名
  def rank
    ranks.revrank(self.id)&.next
  end

  #用户积分
  def score
    ranks.score(self.id).to_i
  end

  #用户签到
  def self.daily_score
    sign_key = "daily_#{Date.today.to_s}"
    Redis::Set.new(sign_key)
  end

  def is_sign?
    self.class.daily_score.member?(id)
  end

  def sign!
    self.class.daily_score << id
    self.checkin_score.incr(id)
  end

  #创建一个用户初始redis值为0
  private
  def init_score
    ranks.incr(self.id, 0)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :find_user, only: [:show]
  def index
    @users = User.all.page(params[:page]).per(2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if verify_rucaptcha?(@user) && @user.save
      login_as @user
      redirect_to admin_users_path
    else
      flash.now[:danger] = "验证码错误"
      render :new
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  def rencent_new_user
    @users = User.rencent_user.page(params[:page]).per(2)
  end

  private

   def user_params
    params.require(:user).permit(:phone, :name, :password, :password_confirmation, :image)
  end

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:get_sms_code]
  before_action :find_user, only: [:show, :edit, :update, :destroy, :person, :checkin]
  before_action :right_user, only: [:edit, :destroy]
  #before_action :require_is_admin, only: [:index, :show]
  #before_action :authenticate!, except: [:index, :show]

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  def show
  end

  def create
    phone, verification_code = user_params.dig("phone"), user_params.dig("verification_code")
    phone_value = Redis::Value.new("#{params[:phone]}", expiration: 2.minutes) #初始化Redis::Value实例且value不为nil, 获取的手机验证码
    if User.exists?(phone: phone)
      flash[:danger] = "用户已注册"
      redirect_to new_user_path
    else
      if phone_value.value.to_s == verification_code.to_s
        @user = User.new(user_params)
        if @user.save
          SmsJob.set(wait: 1.minute).perform_later(@user.phone, @user.name)
          login_as @user
          redirect_to @user
        else
          redirect_to new_user_path
        end
      else
        flash.now[:danger] = "验证码错误"
        render :new       
      end              
    end
  end

  def edit
  end

  def person
  end

  def profile
    @profile = User.friendly.find(params[:id])
  end


  def update
    if @user.update_attributes params.require(:user).permit(:name, :phone, :email, :password, :image, :gender, :signature, :state)
      respond_to do |format|
        format.html{ redirect_to @user }
        format.json{ render json: {user: @user, success: "更新成功"}, status: 200 }
      end
    else
      respond_to do |format|
        format.html{render :edit}
        format.json{render json: { errors: @user.errors.full_message }, status: 400}
      end
    end
  end

  def destroy
     @user.destroy 
     redirect_to root_path
  end

  #短信验证码
  def get_sms_code
    if User.exists?(phone: params[:phone])
      flash[:danger] = "用户已注册" 
      redirect_to new_user_path
    end
    @phone = Redis::Value.new("#{params[:phone]}", expiration: 2.minutes)
    if @phone.value.present? #验证短信是否已发送
      flash[:danger] = "短信发送中, 请稍等"
      redirect_to new_user_path
    else
      @result = { sms_code: @phone.value }
      @phone.value = sms_code
      SmsCodeJob.perform_later(params[:phone], @phone.value)
    end
  end

  def sms_code
    rand(000000..999999)
  end

  def check_email
    if User.exists?(email: params[:email])
      render json: {errors: '邮箱已被占用'}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def check_phone
    if User.exists?(phone: params[:phone])
      render json: {errors: '手机号已被占用'}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def check_name
    if User.exists?(name: params[:name])
      render json: {errors: "用户名已被占用"}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def checkin
    if @user.is_sign?
      return
    else
      @user.sign!
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.permit(:phone, :name, :password, :verification_code, :email, :gender, :signature)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def hide_middle_number(phone)
    phone[3..6] = '****'
    phone
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
- content_for(:title, "注册")
.row
  #bg-img
    = image_tag("background.jpg", style: "width: 1440px")
  .col-md-6.col-md-offset-3
    .panel.panel-wikis
      .panel-heading{style: "height: 40px;"}
        %h2= t('.sign up')
      .panel-body
        = form_tag(users_path, multipart: true, method: :post, id: "errors_message") do 
          .form-group
            %div{class: "input-group"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-user
              = search_field_tag :name, nil, placeholder: "用户名...", class: "form-control", tabindex: 1
            %div{id: "name_taken"}

          .form-group
            %div{class: "input-group"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-envelope
              = search_field_tag :email, nil, placeholder: "邮箱...", class: "form-control", tabindex: 2
            %div{id: "email_taken"}

          .form-group
            %div{class: "input-group"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-phone
              = search_field_tag :phone, nil, placeholder: "手机号码...", class: "form-control", tabindex: 3
            %div{id: "phone_taken"}

          .form-group
            = radio_button_tag(:gender, 'male', :checked => "true" )
            = label_tag(:gender_male, '男')
            = radio_button_tag(:gender, 'female')
            = label_tag(:gender_female, '女')
          
          .form-group
            = text_field_tag :verification_code, nil, size: 6, placeholder: "验证码"
            = button_tag "获取验证码", class: "btn btn-info", id: "get_sms_code"

          .form-group
            %div{class: "input-group password"}
              %div{class: "input-group-addon"}
                %i.glyphicon.glyphicon-lock
              = search_field_tag :password, nil, placeholder: "密码...", class: 'form-control', autocomplete: :off, tabindex: 4
            %i.fa-lg.fa.fa-eye.blink
            
          -#.form-group#ru
            = rucaptcha_input_tag placeholder: "请输入验证码", class: "form-control", tabindex: 5
            = link_to rucaptcha_image_tag, "#", alt: 'Captcha', id: "rucaptcha", remote: true

          -#.form-group
            %span 头像
            = file_field_tag :image, accept: 'image/png, image/jpg, image/jpeg', class: "filestyle", 
            "data-input" =>"false", "date-classButton" => "btn btn-primary", classIcon: "icon-plus"
            
            %div{:id => "target"}

            = link_to "删除文件", '', class: "btn btn-danger btn-xs delete_file"

          %br
            = submit_tag t('.signup'), class: 'btn btn-primary', data: { disable_with: "注册中..." }, tabindex: 7,
              id: "submit"
            |
            = link_to t('.Cancel'), articles_path

:javascript
  $("#get_sms_code").click(function(){
    var phone = $("#phone").val();
    if (phone){
      $.ajax({
        type: "POST",
        url: "/get_sms_code",
        dataType: 'json',
        data: {phone: phone}
      });
      var counter = 120;
      setInterval(function() {
      counter--;
      if (counter >= 0) {
        span = document.getElementById("get_sms_code");
        span.innerHTML = counter+"后点击重新获取";
        $("#get_sms_code").prop("disabled", true)
      }
      if (counter == 0) {
        clearInterval(counter);
        span = document.getElementById("get_sms_code");
        span.innerHTML = "获取验证码";
        $("#get_sms_code").attr("disabled", false);
       
      }
    }, 1000);

    } else{
      alert("请输入手机号码");
    }
    event.preventDefault();
  });
  
  $(document).ready(function(){
    $("#errors_message").validate({
      rules: {
        name: "required",
        email: {
          required: true,
          email: true
        },
        phone: {
          required: true,
          maxlength: 11
        },
        verification_code: {
          required: true,
        },
        password: {
          required: true,
          maxlength: 11,
        }
      },
      messages: {
        name: "请输入用户名",
        email: {
          required: "请输入Email地址",
          email: "请正确输入Email地址",
        },
        phone: {
          required: "请输入手机号",
          maxlength: "11位的手机号",
        },
        verification_code: {
          required: "请输入验证码",
        },
        password: {
          required: "请输入不少于11位的密码",
          maxlength: "最多11位",
        }
      }
    });
  });
  $(":file").filestyle({
    input: false
  });

  $(document).ready(function(){
    $("#submit").attr("disabled", true);
    $("#get_sms_code").attr("disabled", true);

    $('.form-group').on("keyup", function(){
      var getuserName = $("#name").val();
      var getuserEmail = $("#email").val();
      var getuserPhone = $("#phone").val();
      var getuserPassword = $("#password").val(); 
      if(getuserName != "" && getuserEmail != "" && getuserPhone != "" && getuserPassword != ""){
        $("#submit").attr("disabled", false);
        $("#get_sms_code").attr("disabled", false)
      }else{
        $("#submit").attr("disabled", true);
        $("#get_sms_code").attr("disabled", true);
      }
    });
  });

app/views/users/_score.html.haml
- if current_user.is_sign?
  = button_tag '今日已签到', class: 'btn btn-danger btn-sm signed', disabled: true
- else
  = link_to "签到", checkin_user_path(current_user.id), method: :post, class: 'btn btn-success btn-sm', remote: true

app/views/users/checkin.js.erb
$('#checkin').html('<%= escape_javascript(render 'score') %>');
var user_score = $('#score_name').html();
var user_name = "<%= current_user.name %>"
if (user_score == user_name){
  $('#checkin_score').html('<span>当前积分<%= current_user.ranks.score(current_user.id).to_i + current_user.checkin_score.score(current_user.id).to_i %> 分</span>');
}

app/views/users/edit.html.haml
.row
  .col-md-9
    .panel.panel-wikis
      .panel-heading
        编辑

      .panel-body
        = form_for @user, html: { multiple: true, class: 'form-horizontal center', id: "edit", remote: true} do |f|
          .form-group
            .col-sm-6
              - if current_user.image.present?
                = image_tag current_user.image.url, width: 78, height: 78, class: 'img-rounded', id: "avatar", title: "上传新头像"
              - else
                = image_tag "avatar.png", width: 78, height: 78, class: 'img-rounded', id: "avatar", title: "上传新头像"
              = f.file_field :image
          .form-group
            = f.label :name, class: "control-label col-sm-3", require: true
            .col-sm-6
              = f.text_field :name, class: "form-control", require: true

          .form-group
            = f.label :phone, class: "control-label col-sm-3"
            .col-sm-6
              = f.text_field :phone, class: "form-control"

          .form-group
            .col-sm-6{style: "margin-left: 25%"}
              = f.radio_button(:gender, 'male')
              = f.label(:gender_male, '男')
              = f.radio_button(:gender, 'female')
              = f.label(:gender_female, '女')

          .form-group
            = f.label :email, class: "control-label col-sm-3"
            .col-sm-6
              = f.text_field :email, class: "form-control"
            
          .form-group
            = f.label :password, class: "control-label col-sm-3"
            .col-sm-6
              = f.password_field :password, class: "form-control"
          .form-group
            = f.label :signature, class: 'control-label col-md-3'
            .col-sm-6
              = f.text_field :signature, class: 'form-control'
          .form-group
            = f.label :state, class: 'control-label col-md-3'
            .col-md-6
              #province
                = f.hidden_field :state
            
          .form-group
            .col-sm-6.col-sm-push-3
              = f.submit t('.Edit'), class: 'btn btn-primary'
              = link_to t('.Back'), root_path

:javascript
  $(document).ready(function(){
    $("#edit").validate({
      rules: {
        'user[name]': {
          required: true,
        },
        'user[email]': {
          required: true,
          email: true
        },
        'user[phone]': {
          required: true,
          maxlength: 11
        },
        'user[password]': {
          required: false,
          maxlength: 11,
        },
        'user[signature]': {
          required: false
        }
      },
      messages: {
        'user[name]': {
          required: "用户名不能为空",
        },
        'user[email]': {
          required: "邮箱不能为空",
        },
        'user[phone]': {
          required: "手机号不能为空",
        },
        'user[password]': {
          required: "密码不能为空",
        },
        'user[image]': {
          required: "头像不能为空",
        },
        'user[signature]': {
          required: "签名不能为空",
        }
      }
    });
  });

  $(document).ready(function(){
    $("#avatar").click(function(){
      $("#user_image").toggle()
    });
  });

  $(function(){
  $("#province").ProvinceCity()});

  $(document).ready(function(){
    $('#province').on('change', function(){
      var provinceCity = $('#province :selected').text();
      $('input[type=hidden]#user_state').val(provinceCity);
    })
  });

  $('#edit').on('submit', function(e){
    $.ajax({
      type: 'PUT',
      url: $(this).attr('action'),
      data: $(this).serialize(),
      dataType: 'json',
      success: function(data){
      }
    });
    e.preventDefault();
  });

app/views/users/new.html.haml
= render 'form'

app/views/users/new.js.erb
-#$("#rucaptcha").html('<%= j rucaptcha_image_tag %>');

app/views/users/person.html.haml
.row
  .col-md-9
    .panel.panel-wikis
    .panel.panel-default
      .panel-heading.clearfix
        = @user.name
        的文章

      .panel-body
        %ul.article_list.list-group
          .list-group-item-wiki
            - @user.articles.each do |article|
              .media-left
                = image_tag(article.user.image.url, width: 64, height: 64, class: 'img-rounded') if article.user.image.url.present?
              .media-body
                .media-heading
                  = link_to article.title, article
                .media-heading
                  = article.created_at.to_date

app/views/users/profile.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">
              个人资料
            </h3>
          </div>
          <div class="panel-body">
            <div class="user_image">
              <% if current_user.image.present? %>
                <%= image_tag current_user.image.url %>
              <% else %>
                <%= image_tag("avatar.png") %>
              <% end %>
              <div class="user_edit">
                <%= link_to "修改资料", edit_user_path(current_user), class: "btn btn-info btn-sm" %>
              </div>
            </div>
            <div class="user">
              <div class="user_name">
              姓名:
                <%= @profile.name %>
              </div>
              &nbsp
              <div class="user_gender">
              性别:
                <% if current_user.male? %>
                  <div class="male"><i class="fa fa-male"></i></div>
                <% else %>
                  <div class="female"><i class="fa fa-female"></i></div>
                <% end %>
              </div>
              &nbsp
              <div class="user_score">
              当前积分:
              <%= current_user.ranks.score("#{current_user.id}").to_i + current_user.checkin_score.score(current_user.id).to_i %>
              分
              </div>
              &nbsp
              <div class="user_id">
              帐号ID:
                <%= @profile.phone %>
              </div>
              &nbsp
              <div class="user_email">
              email:
                <%= @profile.email %>
              </div>
              &nbsp
              <div class="signature">
              个人签名:
                <%= current_user.signature %>
              </div>
              &nbsp
              <div id="country">
              地区:
                <%= province_format(current_user.state) %>
              </div>
              &nbsp
              <div class="user_created">
              创建时间:
                <%= @profile.created_at.to_date %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.haml
- content_for(:title, @user.name)
= render 'shareds/flash'
.row
  .col-md-9
    .panel.panel-wiki
    .panel.panel-default
      .panel-heading
        .panel-title
        %span用户
      .panel-body
        %ul.list-group
          .list-group-item-wiki
            .media-left
              - if @user.image.present?
                = image_tag(@user.image.url, width: 64, height: 64, class: 'img-rounded')
              - else
                = image_tag("avatar.png", width: 64, height: 64, class: 'img-rounded')
            .media-body
              .media-heading#checkin_score
                当前积分
                = @user.ranks.score(@user.id).to_i + @user.checkin_score.score(@user.id).to_i
                分
              .media-heading
                #score_name= @user.name
  .col-md-4
    .panel.panel-default
      .panel-body
        查看
        = link_to @user.name, release_user_articles_path(@user)
        文章
  