config/routes.rb
Rails.application.routes.draw do

  get 'homes/about'

  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
  # get 'password_resets/new'

  # get 'password_resets/edit'

  require 'sidekiq/web'
  if Rails.env.production?
    mount Sidekiq::Web => 'sidekiq'
  end
  mount ApiRoot => '/api'
  mount GrapeSwaggerRails::Engine, at: "/doc"
  post '/get_sms_code', to: "users#get_sms_code"
  post '/password_resets_code', to: "password_resets#password_resets_code"
  get '/check_name', to: 'users#check_name'
  get '/check_email', to: 'users#check_email'
  get '/check_phone', to: 'users#check_phone'

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end
	
  concern :commentable do
    resources :comments, concerns: [:likeable]
  end

  resources :articles, concerns: [:likeable, :commentable]
  resources :comments, concerns: [:likeable]
  resources :users do
    resources :articles do
    collection do
      get :release
    end
    end
    member do
      get :person
      get :profile
      post :checkin
    end
  end

  resources :sessions
  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end
  resource :password_resets
   
  root "articles#index"
  get "welcome", to: "welcomes#index"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  namespace :admin do
    root "welcomes#index"
    resources :welcomes
    resources :users do
      member do
       get :rencent_new_user
      end
    end
    resources :articles do
      member do
        patch :complete
        post :deny
    end
  end
    resources :comments
    get "signup", to: "users#new", as: "signup"
    get "login", to: "sessions#new", as: "login"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
  end
end

app/models/user.rb
class User < ApplicationRecord 
  #before_destroy :no_referenced_comments
  include Redis::Objects
  sorted_set :ranks, :global => true
  sorted_set :checkin_score, :global => true
  attr_accessor :verification_code
  include Concerns::AuthToken
  extend FriendlyId
  friendly_id :name
  has_secure_password
  has_many :articles, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :notifications
  has_many :likes
  has_many :like_articles, through: :likes, source: :likeable, source_type: "Article"
  validates :name, :phone, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 1..11 }, on: :create
  validates :verification_code, presence: true, on: :create
  validates :email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  #validates :image, attachment_presence: true
  has_attached_file :image, styles: { :original => '250x250>', :small => "200x200#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/png", "image/jpeg"]
  validates_attachment_size :image, less_than: 5.megabytes
  before_create { generate_token(:auth_token) }
  after_create :init_score

  enum gender: ["male", "female"]


  def admin?
    is_admin
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.rencent_user
    User.where("created_at > ?", Time.current.ago(1.day))
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      csv << column_names
    all.each do |user|
      csv << user.attributes.values_at(*column_names)
      end
    end
  end

  def name=(value)
    write_attribute :name, value
    write_attribute :name_lower, value.downcase
  end

  def email=(value)
    write_attribute :email, value
    write_attribute :email_lower, value.downcase
  end

  #postgres 排序
  def self.order_by_ids(ids)
    order_by = ["case"]
    ids.each_with_index.map do |id, index|
      order_by << "WHEN id='#{id}' THEN #{index}"
    end
    order_by << "end"
    order(order_by.join(" "))
  end

  #用户排名
  def rank
    ranks.revrank(self.id)&.next
  end

  #用户积分
  def score
    ranks.score(self.id).to_i
  end

  #用户签到
  def self.daily_score
    sign_key = "daily_#{Date.today.to_s}"
    Redis::Set.new(sign_key)
  end

  def is_sign?
    self.class.daily_score.member?(id)
  end

  def sign!
    self.class.daily_score << id
    self.checkin_score.incr(id)
  end

  #创建一个用户初始redis值为0
  private
  def init_score
    ranks.incr(self.id, 0)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :find_user, only: [:show]
  def index
    @users = User.all.page(params[:page]).per(2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if verify_rucaptcha?(@user) && @user.save
      login_as @user
      redirect_to admin_users_path
    else
      flash.now[:danger] = "验证码错误"
      render :new
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  def rencent_new_user
    @users = User.rencent_user.page(params[:page]).per(2)
  end

  private

   def user_params
    params.require(:user).permit(:phone, :name, :password, :password_confirmation, :image)
  end

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:get_sms_code]
  before_action :find_user, only: [:show, :edit, :update, :destroy, :person, :checkin]
  before_action :right_user, only: [:edit, :destroy]
  #before_action :require_is_admin, only: [:index, :show]
  #before_action :authenticate!, except: [:index, :show]

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "users-#{Date.today}.csv" }
    end
  end

  def show
  end

  def create
    phone, verification_code = user_params.dig("phone"), user_params.dig("verification_code")
    phone_value = Redis::Value.new("#{params[:phone]}", expiration: 2.minutes) #初始化Redis::Value实例且value不为nil, 获取的手机验证码
    if User.exists?(phone: phone)
      flash[:danger] = "用户已注册"
      redirect_to new_user_path
    else
      if phone_value.value.to_s == verification_code.to_s
        @user = User.new(user_params)
        if @user.save
          SmsJob.set(wait: 1.minute).perform_later(@user.phone, @user.name)
          login_as @user
          redirect_to @user
        else
          redirect_to new_user_path
        end
      else
        flash.now[:danger] = "验证码错误"
        render :new       
      end              
    end
  end

  def edit
  end

  def person
  end

  def profile
    @profile = User.friendly.find(params[:id])
  end


  def update
    if @user.update_attributes params.require(:user).permit(:name, :phone, :email, :password, :image, :gender, :signature, :state)
      respond_to do |format|
        format.html{ redirect_to @user }
        format.json{ render json: {user: @user, success: "更新成功"}, status: 200 }
      end
    else
      respond_to do |format|
        format.html{render :edit}
        format.json{render json: { errors: @user.errors.full_message }, status: 400}
      end
    end
  end

  def destroy
     @user.destroy 
     redirect_to root_path
  end

  #短信验证码
  def get_sms_code
    if User.exists?(phone: params[:phone])
      flash[:danger] = "用户已注册" 
      redirect_to new_user_path
    end
    @phone = Redis::Value.new("#{params[:phone]}", expiration: 2.minutes)
    if @phone.value.present? #验证短信是否已发送
      flash[:danger] = "短信发送中, 请稍等"
      redirect_to new_user_path
    else
      @result = { sms_code: @phone.value }
      @phone.value = sms_code
      SmsCodeJob.perform_later(params[:phone], @phone.value)
    end
  end

  def sms_code
    rand(000000..999999)
  end

  def check_email
    if User.exists?(email: params[:email])
      render json: {errors: '邮箱已被占用'}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def check_phone
    if User.exists?(phone: params[:phone])
      render json: {errors: '手机号已被占用'}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def check_name
    if User.exists?(name: params[:name])
      render json: {errors: "用户名已被占用"}, status: 200
    else
      render json: {}, status: 404
    end
  end

  def checkin
    if @user.is_sign?
      return
    else
      @user.sign!
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.permit(:phone, :name, :password, :verification_code, :email, :gender, :signature)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def hide_middle_number(phone)
    phone[3..6] = '****'
    phone
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.haml
.container-fluid
  .row
    .col-md-8.col-md-offset-3.main-content
      .panel.panel-default
        .panel-heading
          .panel-title
          %span所有用户
          .pull-right
            = link_to "Export", users_path(format: "csv")

        .panel-body
          %table.table.table-inverse
            %thead
              %tr
                %th 图片
                %th 姓名
                %th 电话号码
            %tbody
              - @users.each do |user|

                %tr
                  - if user.image.present?
                    %td= image_tag user.image.url, class: 'img-rounded', width: 48, height: 48
                  - else
                    %td= image_tag("avatar.png", class: 'img-rounded', width: 48, height: 48)

                  %td= link_to user.name, admin_user_path(user)

                  %td= hide_middle_number(user.phone)

                  %td
                    = link_to user_path(user), method: :delete, data: { confirm: "Are you sure" } do
                      %i.fa.fa-trash
                      
        =paginate @users

app/views/admin/users/new.html.haml
.main
  .container
    .row
      .col-sm-6.col-md-offset-3
        .panel
          .panel-heading
            %h2= t('.sign up')
          .panel-body
            = simple_form_for [:admin, @user], html: { multipart: true, class: 'user-form' } do |f|
              = render 'shareds/errors'
              = render 'shareds/flash'
              .form-group
                %i.glyphicon.glyphicon-user
                = f.label :name, class: "control-label"
                = f.text_field :name, class: "form-control"

              .form-group
                %i.glyphicon.glyphicon-phone
                = f.label :phone, class: "control-label"
                = f.text_field :phone, class: "form-control"

              .form-group
                %i.glyphicon.glyphicon-eye-open
                = f.label :password, class: "control-label"
                = f.password_field :password, class: "form-control"

              .form-group
                %i.glyphicon.glyphicon-eye-open
                = f.label :password_confirmation, class: "control-label"
                = f.password_field :password_confirmation, class: "form-control"

              .form-group#ru
                = rucaptcha_input_tag placeholder: "请输入验证码", class: "form-control"
                = link_to rucaptcha_image_tag, "#", alt: 'Captcha', id: "rucaptcha", remote: true

              = f.file_field :image

              %br

              = f.submit "注册", data: { disable_with: "注册中..." }, class: 'btn btn-primary'
  

app/views/admin/users/rencent_new_user.html.haml
.container-fluid
  .row
    .col-md-8.col-md-offset-3
      .panel.panel.default
        .panel-heading
          .pane-title
            %span 最近用户
          
          .panel-body
            %table.table.table-inverse
              %thead
                %tr
                  %th ID
                  %th 姓名
                  %th 电话
                  %th 时间
              %tbody
                - @users.each do |r|
                  %tr
                    %td= r.id
                    %td= r.name
                    %td= r.phone
                    %td= r.created_at.to_date
        = paginate @users

app/views/admin/users/show.html.haml
- content_for(:title, @user.name)
.main
  .container
    .row
      .col-md-8.col-md-offset-3
        .panel.panel-default
          .panel-heading
            .panel-title
            %span用户
          .panel-body
            %table.table.table-striped
              %thead
                %tr
                  %th ID
                  %th电话
              %tbody
                %tr
                  %td= @user.id
                  %td= @user.phone